services:
  backend:
    build:
      context: ./backend
    restart: always
    env_file:
      - ./backend/.env
    expose:
      - "8000"
    networks:
      - app-network

  frontend:
    build:
      context: ./frontend
      args:
        VITE_API_URL: https://buld.site
    restart: always
    depends_on:
      - backend
    networks:
      - app-network

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx/prod.conf:/etc/nginx/conf.d/default.conf:ro
      - /etc/letsencrpyt:/etc/letsencrypt:ro
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - backend
      - frontend
    networks:
      - app-network

networks:
  app-network:
